Default: &defaults
  host: "localhost"
  port: 3000
  copyright: (c) Paul van der Walt
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  approot: "http://beta.denknerd.org"
  port: 4321
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "https://denknerd.org"
  port: 4321
  <<: *defaults
