Default: &defaults
  database: denknerd.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Test:
  database: denknerd_test.sqlite3
  <<: *defaults

Staging:
  database: denknerd_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: denknerd_production.sqlite3
  poolsize: 100
  <<: *defaults
